services:

    ####################################################################################################
    # web
    ####################################################################################################
    web:
        build: .
        container_name: web
        restart: always
        image: deep_api
        ports:
            - 5173:5173
            - 9003:9003
        networks:
            - deep_network
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy

        command: bash -c "php artisan migrate --seed && php-fpm"
        volumes:
            - laravel_data:/var/www

    ####################################################################################################
    # queue_worker
    ####################################################################################################
    queue_worker:
        image: deep_api
        container_name: queue_worker
        restart: always
        command: php artisan queue:work redis
        networks:
            - deep_network
        depends_on:
            - web

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - laravel_data:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web
        networks:
            - deep_network

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    mysql:
        image: mysql:8.1
        container_name: mysql
        restart: always
        ports:
            - 3306:3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s
        volumes:
            - db_data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        env_file:
            - ./.env
        networks:
            - deep_network

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        env_file:
            - ./.env
        networks:
            - deep_network

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s
        networks:
            - deep_network

    ####################################################################################################
    # Mailpit (for email testing)
    ####################################################################################################
    mail:
        image: axllent/mailpit:latest
        ports:
            - 8025:8025
            - 1025:1025
        networks:
            - deep_network

volumes:
    db_data:
    redis_data:
    laravel_data:


networks:
    deep_network:
        driver: bridge
