name: Deep API CI/CD
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:11.0
        ports:
          - 23306:3306
        env:
          MARIADB_AUTO_UPGRADE: 1
          MARIADB_DATABASE: test_db
          MARIADB_ROOT_PASSWORD: root
          MARIADB_USER: dbuser
          MARIADB_PASSWORD: root
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: redis, gd, pdo, pdo_mysql
      - uses: actions/checkout@v3

      # - name: Shutdown Ubuntu MySQL (SUDO)
      #   run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: php artisan key:generate
    
      - name: Run Migrations
        env:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_PORT: 23306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_PORT: 23306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test

      - name: Run frontend tests
        run: |
              npm --silent install
              # npm --silent test
              npm --silent run build